schools/mdapioutput/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Teacher_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher ID</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

schools/mdapioutput/objects/Discipline__c.object
<CustomObject>
    <label>Discipline</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disciplines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Disciplines</relationshipLabel>
        <relationshipName>Disciplines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

schools/mdapioutput/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Type__c</fullName>
        <label>School Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Preschool</fullName>
                </value>
                <value>
                    <fullName>Elementary</fullName>
                </value>
                <value>
                    <fullName>Middle</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>College</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

schools/mdapioutput/objects/Teacher__c.object
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Discipline_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Discipline ID</label>
        <referenceTo>Discipline__c</referenceTo>
        <relationshipLabel>Teachers (Discipline ID)</relationshipLabel>
        <relationshipName>Teachers1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Teachers</relationshipLabel>
        <relationshipName>Teachers1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

schools/force-app/main/default/classes/TestObjectsCreator.cls
public with sharing class TestObjectsCreator {
    public TestObjectsCreator() {
        School__c school = createSchool('TestSchool', 'Some Test Address', 'High school');
        System.debug(school);
    }

    public School__c createSchool(String name, String address, String type) {
        School__c school = new School__c(Name = name, Address__c = address, School_Type__c = type);
        insert school;

        return school;
    }

    public Category__c createCategory(String name, ID schoolId, ID teacherId) {
        Category__c category = new Category__c(Name = name, School__c = schoolId, Teacher_ID__c = teacherId);
        insert category;

        return category;
    }

    public Discipline__c createDiscipline(String name, ID schoolId) {
        Discipline__c discipline = new Discipline__c(Name = name, School__c = schoolId);
        insert discipline;

        return discipline;
    }

    public Teacher__c createTeacher(String name, ID schoolId, ID disciplineId) {
        Teacher__c teacher = new Teacher__c(Name = name, School__c = schoolId, Discipline_ID__c = disciplineId);
        insert teacher;

        return teacher;
    }
}