schools/mdapioutput/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Teacher_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher ID</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

schools/mdapioutput/objects/Discipline__c.object
<CustomObject>
    <label>Discipline</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disciplines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Disciplines</relationshipLabel>
        <relationshipName>Disciplines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

schools/mdapioutput/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Type__c</fullName>
        <label>School Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Preschool</fullName>
                </value>
                <value>
                    <fullName>Elementary</fullName>
                </value>
                <value>
                    <fullName>Middle</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>College</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

schools/mdapioutput/objects/Student__c.object
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

schools/mdapioutput/objects/Teacher__c.object
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Discipline_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Discipline ID</label>
        <referenceTo>Discipline__c</referenceTo>
        <relationshipLabel>Teachers (Discipline ID)</relationshipLabel>
        <relationshipName>Teachers1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Teachers</relationshipLabel>
        <relationshipName>Teachers1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admission Director</fullName>
                </value>
                <value>
                    <fullName>Athletic Coach</fullName>
                </value>
                <value>
                    <fullName>Autism/Behavior Specialist</fullName>
                </value>
                <value>
                    <fullName>Communication Specialist</fullName>
                </value>
                <value>
                    <fullName>Librarian</fullName>
                </value>
                <value>
                    <fullName>Music Teacher</fullName>
                </value>
                <value>
                    <fullName>Psychologist</fullName>
                </value>
                <value>
                    <fullName>Science Teacher</fullName>
                </value>
                <value>
                    <fullName>Social Worker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

schools/mdapioutput/classes/TestObjectsCreator.cls
public with sharing class TestObjectsCreator {
    public TestObjectsCreator() {

        

        System.debug(school);
        System.debug(disciplines);
    }

    public static School__c createSchool(String name, String address, String type) {
        School__c school = new School__c(Name = name, Address__c = address, School_Type__c = type);
        insert school;

        return school;
    }

    public static Category__c createCategory(String name, ID schoolId, ID teacherId) {
        Category__c category = new Category__c(Name = name, School__c = schoolId, Teacher_ID__c = teacherId);
        insert category;

        return category;
    }



    public static List<Student__c> createStudents(String name, ID schoolId, Integer studentsCount) {
        List<Student__c> students = new List<Student__c>();
        for (Integer i = 0; i < length; i++) {
           
        }
        Student__c student = new Student__c(Name = name, School__c = schoolId, Discipline_ID__c = disciplineId);
        insert teacher;

        return teacher;
    }

    public static List<Discipline__c> createDisciplines(ID schoolId, ID teacherId, List<Student__c> students) {
        Discipline__c math = getDiscipline('Math', schoolId, teacherId, students);
        Discipline__c history = getDiscipline('History', schoolId, teacherId, students);
        Discipline__c geography = getDiscipline('Geography', schoolId, teacherId, students);
        Discipline__c[] disciplines = new Discipline__c[] { math, history, geography };
        insert disciplines;

        insert disciplines;
    }

    public static Discipline__c getDiscipline(String name, ID schoolId) {
        Discipline__c discipline = new Discipline__c(Name = name, School__c = schoolId);

        return discipline;
    }

    public static Teacher__c getTeacher(String name, String title, ID schoolId, ID disciplineId) {
        Teacher__c teacher = new Teacher__c(Name = name,  Title__c = title,
                                            School__c = schoolId, Discipline_ID__c = disciplineId);
        insert teacher;

        return teacher;
    }

    public static Student__c getStudent(String name, ID schoolId) {
        Student__c student = new Student__c(Name = name, School__c = schoolId);

        return student;
    }
}