schools/mdapioutput/objects/Profile__c.object
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

schools/force-app/main/default/objects/Profile__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

schools/mdapioutput/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

schools/mdapioutput/objects/Teacher__c.object
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Profile_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Profile_ID</label>
        <referenceTo>Profile__c</referenceTo>
        <relationshipLabel>Teachers</relationshipLabel>
        <relationshipName>Teachers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Teachers</relationshipLabel>
        <relationshipName>Teachers1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admission Director</fullName>
                </value>
                <value>
                    <fullName>Athletic Coach</fullName>
                </value>
                <value>
                    <fullName>Autism/Behavior Specialist</fullName>
                </value>
                <value>
                    <fullName>Communication Specialist</fullName>
                </value>
                <value>
                    <fullName>Librarian</fullName>
                </value>
                <value>
                    <fullName>Music Teacher</fullName>
                </value>
                <value>
                    <fullName>Psychologist</fullName>
                </value>
                <value>
                    <fullName>Science Teacher</fullName>
                </value>
                <value>
                    <fullName>Social Worker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

schools/force-app/main/default/classes/dao/TeacherDao.cls
public class TeacherDao {
    
    public static Teacher__c save(String fullName, Id schoolId, String title, Profile__c profile) {
         Teacher__c teacher = new Teacher__c(Name = fullName, 
                                            School__c = schoolId, 
                                            Title__c = title);
        if (profile != null) {
            teacher.Profile_ID__c = profile.Id;
        }

        Database.insert(teacher);

        return teacher;
    }

    public static Teacher__c getById(ID teacherId) {
        Teacher__c teacher = [
                                SELECT ID, Name, Title__c, Profile_ID__c
                                  FROM Teacher__c
                                 WHERE Id = :teacherId
                              ORDER BY Name
                            ];
        
        return teacher;
    }

    // get all teachers in specific school. 
    // We can save the school Id we are in into the browser local storage
    public static findAll(ID schoolId) {
        List<Teacher__c> teachers = [SELECT ID, Name FROM Teacher__c WHERE School__c == schoolId];

        return teachers;
    }
}