schools/mdapioutput/objects/Profile__c.object
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

schools/force-app/main/default/objects/Profile__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

schools/mdapioutput/objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

schools/mdapioutput/objects/Student__c.object
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Category_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category ID</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Profile ID</label>
        <referenceTo>Profile__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

schools/mdapioutput/classes/StudentDao.cls
public class StudentDao {

   public static Student__c save(String fullName, Id schoolId, Id categoryId, Profile__c profile) {
         Student__c student = new Student__c(Name = fullName, 
                                            School__c = schoolId, 
                                            Category_ID__c = categoryId);
        if (profile != null) {
            student.Profile_ID__c = profile.Id;
        }

        Database.insert(student);

        return student;
    }

    // get all students in specific school. 
    // We can save the school Id we are in into the browser local storage
    public static findAll(ID schoolId) {
        List<Student__c>  students = [SELECT ID, Name FROM Student__c WHERE School__c == schoolId];

        return students;
    }
}