schools/mdapioutput/objects/Student__c.object
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

schools/mdapioutput/objects/Teacher_Student__c.object
<CustomObject>
    <label>Teacher Student</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Student Teacher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Student_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Student ID</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Teacher Students</relationshipLabel>
        <relationshipName>Teacher_Students</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teacher_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Teacher ID</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Teacher Students</relationshipLabel>
        <relationshipName>Teacher_Students</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

schools/force-app/main/default/objects/Teacher_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Teacher Students</relationshipLabel>
    <relationshipName>Teacher_Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

schools/force-app/main/default/classes/entities/Student.cls
public class Student extends SchoolAccount {

    private Id categoryId {get; set;}
    public List<Teacher> teachers {get; set;}
    
    public Student(String fullName, Id schoolId) {
        super(fullName, schoolId);
        this.teachers = new List<Teacher>();
    }

    public void addTeacher(Teacher teacher) {
        this.createJunction(this.accountId, teacher.accountId);
        this.teachers.add(teacher);
    }

    public void addCategory(Id categoryId) {
        this.categoryId = categoryId;
    }

    protected override sObject save() {
        Student__c student = StudentDao.save(super.fullName, super.schoolId, this.categoryId, super.profile);

        return student;
    } 

    private void createJunction(Id studentId, Id teacherId) {
        Teacher_Student__c junctionObj = new Teacher_Student__c(Student_ID__c = studentId, Teacher_ID__c = teacherId);

        Database.insert(junctionObj);
    }
}